apiVersion: v1
kind: ServiceAccount
metadata:
  name: probeep
  namespace: lucca
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: probeep-role
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - list
  - get
  - update
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: probeep
subjects:
- kind: ServiceAccount
  name: probeep
  namespace: lucca
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: probeep-role
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: probeep
  namespace: lucca
spec:
  selector:
    matchLabels:
      app: probeep
  template:
    metadata:
      labels:
        app: probeep
    spec:
      containers:
      - name: probeep
        image: probeep:latest
        imagePullPolicy: Always
        env:
        - name: CHECK_NAMESPACE
          value: default
        - name: CHECK_ENDPOINT
          value: consul
        - name: CHECK_PORT
          value: "8500"
        - name: PERIOD_SECONDS
          value: "10"
        - name: TIMEOUT_SECONDS
          value: "3"
        resources:
          limits:
            memory: "50Mi"
            cpu: "20m"
          requests:
            memory: "20Mi"
            cpu: "10m"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 1
      imagePullSecrets:
      - name: lucca-registry
      restartPolicy: Always
      terminationGracePeriodSeconds: 20
      serviceAccountName: probeep
---
apiVersion: v1
kind: Endpoints
metadata:
  name: consul
  annotations:
    lucca.net/probe-ep-hostnames: '["hostname.to.resolve.example.com","hostname.to.resolve2.example.com","hostname.to.resolve3.example.com"]'
subsets: []
---
apiVersion: v1
kind: Service
metadata:
  name: consul
spec:
  ports:
  - name: http
    port: 8500