name: build-docker

on: [push, pull_request]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          
  gitversion:
    runs-on: ubuntu-latest
    outputs:
      fullSemver: ${{ steps.gitversion.outputs.fullSemVer }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
            versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build the Docker image
        run: docker build . -t probeep

  publish-docker:
    runs-on: ubuntu-latest
    needs: [gitversion, login, build-docker]
    env:
      IMAGE_TAG: ${{ secrets.REGISTRY }}/lucca/k8s/probeep:${{ needs.gitversion.outputs.fullSemVer }}
    steps:
      - name: Tag
        run: docker tag probeep $IMAGE_TAG
      
      - name: Publish
        run: docker push $IMAGE_TAG